import type { Metadata } from "next";
import Link from "next/link";
import { Card, Container, Section } from "@/components/ui";
import { Icon } from "@/components/ui/Icon";
import { RestrictedLookup } from "@/components/product/Browsers";

export const metadata: Metadata = {
  title: "Prohibited & restricted items",
  description:
    "What you can and cannot ship across a border, what documentation restricted goods need, and what happens if a parcel is seized.",
  alternates: { canonical: "/legal/prohibited-items" },
};

const DOCS = [
  ["Commercial invoice", "Every parcel. Lists contents, value and origin.", "Generated by Shipmart automatically."],
  ["Certificate of origin", "Where a trade agreement affects the duty rate.", "Issued by your chamber of commerce."],
  ["UN38.3 test summary", "Anything containing a lithium battery.", "From your battery or device manufacturer."],
  ["Phytosanitary certificate", "Plants, seeds and some wood products.", "From your national plant health authority."],
  ["Safety data sheet", "Cosmetics, aerosols and flammable liquids.", "From the product manufacturer."],
];

export default function ProhibitedItemsPage() {
  return (
    <>
      <Container className="pt-stack-xl">
        <div className="max-w-3xl">
          <h1 className="font-display-lg text-display-lg text-on-surface mb-stack-md">
            What you can and cannot ship.
          </h1>
          <p className="font-body-lg text-body-lg text-on-surface-variant">
            Rules vary by destination and change without much warning. This page is a starting point, not a
            legal ruling — if your product is near a line, ask us before you ship it.
          </p>
        </div>
      </Container>

      <Section className="pt-0"><RestrictedLookup /></Section>

      <Section tone="low">
        <h2 className="font-headline-lg text-headline-lg text-on-surface mb-stack-lg">Documents restricted goods need</h2>
        <div className="flex flex-col gap-stack-sm">
          {DOCS.map(([name, when, where]) => (
            <Card key={name} className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <h3 className="font-label-md text-label-md text-on-surface">{name}</h3>
              <p className="font-body-sm text-body-sm text-on-surface-variant">{when}</p>
              <p className="font-body-sm text-body-sm text-on-surface-variant">{where}</p>
            </Card>
          ))}
        </div>
      </Section>

      <Section>
        <h2 className="font-headline-lg text-headline-lg text-on-surface mb-stack-lg">If a parcel is stopped</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-gutter">
          {[
            ["Detained", "Customs ask for a document. We tell you which one and who has to produce it. Usually resolved in a day."],
            ["Returned", "The goods are legal but not admissible as declared. Return freight is billed at the original lane rate."],
            ["Seized and destroyed", "Prohibited goods. There is no compensation and no appeal — the authority owns that decision."],
          ].map(([title, body]) => (
            <Card key={title} className="h-full">
              <h3 className="font-headline-sm text-headline-sm text-on-surface mb-stack-sm">{title}</h3>
              <p className="font-body-md text-body-md text-on-surface-variant">{body}</p>
            </Card>
          ))}
        </div>
      </Section>

      <Section tone="dark" className="text-center">
        <Icon name="alert" size={32} className="text-on-dark-primary mx-auto mb-stack-md" />
        <h2 className="font-headline-lg text-headline-lg text-surface-bright mb-stack-md">
          Not sure about your product? Ask before you ship.
        </h2>
        <p className="font-body-md text-body-md text-on-dark-muted max-w-xl mx-auto mb-stack-lg">
          A five-minute question is cheaper than a seized shipment.
        </p>
        <Link
          href="/contact"
          className="inline-flex items-center justify-center rounded font-label-md text-label-md min-h-[44px] px-8 py-4 bg-surface-bright text-on-secondary-fixed hover:bg-surface-container-low transition-colors"
        >
          Ask about an item
        </Link>
      </Section>
    </>
  );
}
